import type { Metadata } from 'next'

import { draftMode } from 'next/headers'

import { VisualEditing } from 'next-sanity'
import { Toaster } from 'react-hot-toast'

import DisableDraftMode from '@/components/DisableDraftMode'
import ChatIcon from '@/components/new/ChatIcon'
import { SanityLive } from '@/sanity/lib/live'

import Footer from '@/components/Footer'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Ecommerce App for Shoppers',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      {(await draftMode()).isEnabled && (
        <>
          <DisableDraftMode />
          <VisualEditing />
        </>
      )}
      <Header />
      {children}
      <Footer />
      <Toaster
        position="bottom-right"
        toastOptions={{
          style: {
            background: '#000000',
            color: '#fff',
          },
        }}
      />
      <SanityLive />
      <ChatIcon />
    </div>
  )
}
