import { Metadata } from 'next'

/**
 * Propiedades para el componente RootLayout.
 * 
 * @property {React.ReactNode} children - Elementos secundarios que serán renderizados dentro del layout raíz.
 */
interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Ecommerce Backend',
  description: 'Generated by create next app',
}

/**
 * Componente de layout raíz para la sección de administración del estudio.
 *
 * @param {RootLayoutProps} props - Propiedades del componente.
 * @param {React.ReactNode} props.children - Elementos secundarios que serán renderizados dentro del layout.
 * @returns {JSX.Element} Un contenedor que envuelve los elementos hijos proporcionados.
 */
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return <div>{children}</div>
}

export default RootLayout
